---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-front
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: magpie-frontend
          image: reddddddddd/hfte-frontend:6
          ports:
            - containerPort: 5173

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: ns-front
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 5173
  selector:
    app: frontend
