---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-admin # Name of this app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/here-for-the-experience/deployment.git # This should be the URL of the this Git repository
    targetRevision: HEAD
    path: environments/dev/app-frontend-admin # path to the deployment of this app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
